from loguru import logger

from core.task_planner import TaskPlanner
from core.command_processor import CommandProcessor
from core.intent_classifier import IntentClassifier
from core.agent_loop import AgentLoop
from core.goal_executor import GoalExecutor
from core.goal_verifier import GoalStatus

from skills.manager.skill_manager import SkillManager
from automation.automation_engine import AutomationEngine

from state.environment_state import EnvironmentState

from system.services.ui_controller import UIController
from core.wait_engine import WaitEngine

from core.execution_context import ExecutionContext


class AgentController:

    def __init__(
        self,
        vision_manager,
        memory_manager,
        context_manager,
        brain_manager,
        conversation_manager,
        execution_context,
        system_manager=None,
    ):

        logger.info("[AgentController] Initializing")

        self.command_processor = CommandProcessor()

        self.execution_context = execution_context

        self.vision = vision_manager
        # Cached VisionFrame
        self.latest_frame = None

        self.memory = memory_manager

        self.context = context_manager

        self.brain = brain_manager

        self.conversation = conversation_manager

        self.system = system_manager

        self.ui_controller = UIController()
        self.wait_engine = WaitEngine(
            vision_manager=self.vision,
            ui_controller=self.ui_controller,
            execution_context=self.execution_context,
        )

        self.skill_dependencies = {
            "automation": None,
            "vision_manager": self.vision,
            "memory": self.memory,
            "brain": self.brain,
            "system": self.system,
            "ui_controller": self.ui_controller,
            "execution_context": self.execution_context,
            "screen_observer": getattr(self.vision, "observer", None),
            "wait_engine": self.wait_engine,
        }
        self.skills = SkillManager(self.skill_dependencies)
        self.intent_classifier = IntentClassifier(
            brain_manager=self.brain,
            command_processor=self.command_processor,
            available_skills=[],
        )
        self.planner = TaskPlanner(
            brain_manager=self.brain,
            command_processor=self.command_processor,
            available_skills=[],
            execution_context=self.execution_context,
            skill_manager=self.skills,
        )

        self.executor = GoalExecutor(
            skill_manager=self.skills,
            dependencies=self.skill_dependencies,
            execution_context=self.execution_context,
        )
        self.env_state = EnvironmentState()

        self.agent_loop = AgentLoop(
            self.planner, self.executor, self.vision, self.context, self.ui_controller
        )

        self.automation = AutomationEngine(self.executor)

        # Inject services into SkillManager
        self.skills.dependencies["automation"] = self.automation

    async def initialize(self):

        logger.info("[AgentController] Starting initialization")

        # ----------------------------
        # Load all skills
        # ----------------------------

        await self.skills.initialize()

        logger.info(
            f"[AgentController] SkillManager loaded {self.skills.skill_count()} skills"
        )

        # ----------------------------
        # Update IntentClassifier
        # ----------------------------

        self.intent_classifier.available_skills = self.skills.list_skills()

        # ----------------------------
        # Update Planner
        # ----------------------------

        self.planner.set_available_skills(self.skills.list_skills())

        logger.info(
            f"[AgentController] Planner loaded {len(self.planner.available_skills)} skills"
        )

        return True

    # ──────────────────────────────────────────────────────────
    # Helper — screen summary
    # ──────────────────────────────────────────────────────────

    def _get_screen_summary(self) -> str:
        """
        Return the latest semantic summary generated by the
        Vision Pipeline.
        """

        frame = self.vision.get_latest_frame()

        if frame is None:
            return "No visual information available."

        self.latest_frame = frame

        return frame.summary

    # ──────────────────────────────────────────────────────────
    # Main command processor
    # ──────────────────────────────────────────────────────────

    def process_command(self, command: str) -> str:

        logger.info(f"[AgentController] Processing command: {command}")

        if not self.skills.skill_count():

            logger.warning("[AgentController] Skills not initialized")

            return "Skills are still loading."

        # User message history mein add karo
        self.conversation.add_user_message(command)

        intent_result = self.intent_classifier.classify(command)

        intent = (
            intent_result["intent"]
            if isinstance(intent_result, dict)
            else intent_result
        )

        # ── Chat mode ─────────────────────────────────────────
        if intent == "chat":
            logger.info("[AgentController] Chat intent detected")

            summary = self._get_screen_summary()
            history = self.conversation.get_history_for_brain()

            # Current message history se nikalo — brain separately bhejega
            history_without_last = history[:-1] if history else []

            answer = self.brain.ask(
                command,
                context=summary,
                conversation_history=history_without_last,  # pichla context
            )

            if not answer:
                answer = "I couldn't generate a response."

            # Response history mein save karo
            self.conversation.add_assistant_message(answer)
            return answer

        # ── Goal mode ─────────────────────────────────────────
        if self.is_goal_command(command):
            logger.info(
                "[AgentController] Goal-style command detected; starting agent loop"
            )
            self.agent_loop.run_goal(command)
            response = "Working on it."
            self.conversation.add_assistant_message(response)
            return response

        # ── Simple automation mode ─────────────────────────────

        system_context = self.context.get_system_context()

        vision_frame = self.vision.get_latest_frame()

        if vision_frame is None:
            response = "Vision system is not ready."
            self.conversation.add_assistant_message(response)
            return response

        self.latest_frame = vision_frame

        summary = vision_frame.summary

        logger.info(f"[AgentController] Screen summary:\n{summary}")

        self.env_state.update(
            system_context,
            vision_frame,
        )

        related_memory = self.memory.search_memory(command)

        logger.info(f"[AgentController] Related memory: {related_memory}")

        ui_elements = vision_frame.ui_tree.elements if vision_frame.ui_tree else []

        patterns = self.vision.ui_memory.get_patterns(
            system_context.get(
                "active_window",
                "unknown",
            )
        )

        combined_context = {
            "system": system_context,
            "vision": vision_frame,
            "ui_elements": ui_elements,
            "memory": related_memory,
            "known_patterns": patterns,
            "screen_summary": summary,
        }

        plan = self.planner.create_plan(command, combined_context)
        logger.info(f"[AgentController] Plan generated: {plan}")

        if not plan:
            logger.warning("[AgentController] No plan generated")
            response = "I couldn't figure out how to do that."
            self.conversation.add_assistant_message(response)
            return response

        try:

            result = self.executor.execute_plan(
                plan,
                goal=command,
            )

        except Exception:

            logger.exception("GoalExecutor failed, falling back.")

            result = self.execute_plan_with_feedback(
                command,
                plan,
            )

        if result == "error":
            response = "I tried, but that action failed."
        else:
            response = "Task completed."

        self.conversation.add_assistant_message(response)
        return response

    # ──────────────────────────────────────────────────────────
    # Plan execution with vision feedback
    # ──────────────────────────────────────────────────────────

    def execute_plan_with_feedback(self, command: str, plan: list, fail_count=0):

        step_count = 0
        max_steps = self.planner.max_plan_steps
        max_failures = 3

        for step in plan:

            if step_count >= max_steps:
                logger.warning("[AgentController] Max steps reached; stopping")
                return "error"

            step_count += 1
            skill = step.get("skill")
            logger.info(f"[AgentController] Executing step: {skill}")

            result = self.executor.execute_step(step)
            self.env_state.set_action_feedback(step, result)
            logger.info(f"[AgentController] Skill result: {result}")

            system_context = self.context.get_system_context()

            vision_frame = self.vision.get_latest_frame()

            if vision_frame is None:
                logger.error("[AgentController] Vision unavailable during execution")
                return "error"

            self.latest_frame = vision_frame

            summary = vision_frame.summary

            ui_elements = vision_frame.ui_tree.elements if vision_frame.ui_tree else []

            observation = {
                "system": system_context,
                "vision": vision_frame,
                "ui_elements": ui_elements,
                "last_result": result,
                "screen_summary": summary,
            }

            logger.debug(f"[AgentController] Updated screen: {summary}")

            if result == "error":
                fail_count += 1
                if fail_count >= max_failures:
                    logger.error("[AgentController] Too many failures; aborting")
                    return "error"
                logger.warning("[AgentController] Step failed; replanning")
                new_plan = self.planner.create_plan(command, observation)
                if new_plan:
                    return self.execute_plan_with_feedback(
                        command, new_plan, fail_count=fail_count
                    )
                return "error"

        final_observation = self.executor.observe()
        
        goal_result = self.executor.verify_goal(command, final_observation)

        if goal_result:

            if goal_result.status == GoalStatus.FAILED:
                logger.error(
                    f"[AgentController] Goal verification failed: {goal_result.reason}"
                )
                return "error"

            if goal_result.status == GoalStatus.PARTIAL:
                logger.warning(
                    f"[AgentController] Goal partially verified: {goal_result.reason}"
                )
                return "error"

        logger.info("[AgentController] Task execution completed")
        return "success"

    # ──────────────────────────────────────────────────────────
    # Goal detection
    # ──────────────────────────────────────────────────────────

    def is_goal_command(
        self,
        command: str,
    ) -> bool:
        """
        Detect long-running autonomous tasks.

        Normal actions should stay in:
        Planner -> Executor -> Skills

        Only continuous tasks use AgentLoop.
        """

        command = command.lower().strip()

        autonomous_keywords = [
            "monitor",
            "keep watching",
            "watch for",
            "track continuously",
            "alert me when",
            "notify me when",
            "keep checking",
        ]

        return any(keyword in command for keyword in autonomous_keywords)
